export const CONTENT = {
    intro: {
        heading: "Let Free Your Creativity with Our Intuitive Content Creator",
        description: "No design degree is required! Effortlessly craft and design stunning and captivating content using our user-friendly creative editor. With our drag-and-drop technology, anyone can create amazing marketing materials in.",
    },
    login: {
        welcome: "Welcome Octopus!",
        subtitle: "Manage your smart signage, watch your company grow.",
        emailLabel: "E-mail Address*",
        emailPlaceholder: "Enter your e-mail address",
        passwordLabel: "Password*",
        passwordPlaceholder: "Enter your password",
        rememberMe: "Remember me?",
        buttonText: "Login",
        loadingText: "Giriş Yapılıyor...",
        successMessage: "Giriş Başarılı! Yönlendiriliyorsunuz...",
    },
    header: {
        logoAlt: "Octopus Logo",
        role: "Yönetici",
        accountLabel: "Hesap Hesabı",
        profileInfo: "Profil Bilgileri",
        logout: "Çıkış Yap",
    },
    sidebar: {
        searchPlaceholder: "Ürün ara...",
        categoriesTitle: "Kategoriler",
        clearFilter: "Temizle",
    },
    products: {
        pageTitle: "Tüm Ürünler",
        searchResultsFor: "için sonuçlar",
        productsFound: "ürün bulundu",
        notFound: "Ürün Bulunamadı",
        notFoundDescription: "Arama kriterlerinizi değiştirerek tekrar deneyebilirsiniz.",
        addToCart: "Sepete Ekle",
        prev: "Prev",
        next: "Next",
    },
    productDetail: {
        notFound: "Ürün Bulunamadı",
        goBack: "Ürünlere Geri Dön",
        selectColor: "Renk Seç:",
        colorSilver: "Silver",
        colorBlack: "Black",
        selectFeature: "Özellik Seç:",
        featureTitle: "Ürün Özellik 1",
        featureDescription: "Lorem Ipsum Dolar Sit Amet",
        commentsTitle: "Ürün Yorumları",
        showMore: "Daha fazla göster",
        viewAll: "Tümünü Gör",
        noComments: "Henüz bu ürün için bir yorum yapılmamış.",
        orderSummary: "Sipariş Özeti",
        addToCart: "Sepete Ekle",
    },
    common: {
        logoAlt: "Octopus Logo",
        illustrationAlt: "Design collaboration illustration",
    },
    error: {
        title: "Bir Şeyler Yanlış Gitti",
        message: "Beklenmedik bir hata oluştu. Lütfen sayfayı yenilemeyi deneyin veya ana sayfaya dönün.",
        retry: "Tekrar Dene",
        goHome: "Ana Sayfaya Dön",
    },
    notFound: {
        title: "Sayfa Bulunamadı",
        message: "Aradığınız sayfa mevcut değil veya taşınmış olabilir.",
        goHome: "Ana Sayfaya Dön",
    },
} as const;
